#!/usr/bin/expect -f

set timeout 600
set remote_host "172.16.252.109"
set remote_user "root"
set remote_pass "stvy~J66eumjdrN"
set image [lindex $argv 0]

if { $argc != 1 } {
    puts "Usage: $argv0 <image_name:tag>"
    exit 1
}

spawn ssh -o StrictHostKeyChecking=no $remote_user@$remote_host "docker save $image"

expect {
    "password:" {
        send "$remote_pass\r"
        exp_continue
    }
    eof {
        exit 0
    }
}